repos:
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
      require_serial: true
      exclude: 'vendored|_vispy'
      stages: [commit]
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: pytest -v
      language: system
      types: [python]
      files: 'test_'
      stages: [push]
      pass_filenames: false
